### PR TITLE
New github action to build and upload the ide extension.

### PR DESCRIPTION
**Pull request by karolh2000**
## Description
New github action to build and upload the ide extension.

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia-vscode-extension/issues).

### Code Contributions

- [x] I've run [pre-commit.sh](https://github.com/pyrsia/pyrsia-vscode-extension/blob/main/pre-commit.sh) successfully.

### CODE REVIEW

**Comment by karolh2000** [comment]
https://github.com/pyrsia/pyrsia-vscode-extension/issues/11

**Review by sbtaylor15 — APPROVED** [review]
/lgtm

**Comment by karolh2000** [comment]
> /lgtm

Hi @sbtaylor15 , I was hoping that maybe you can suggest a solution how to upload the binaries to https://vscode.pyrsia.io/ or point me to a GitHub action that does something similar. Thanks!

**Comment by sbtaylor15** [comment]
@karolh2000 Here are the GH steps for the upload.  You will need to create a new script modeled from the chartmuseum.sh to get the new installer into the right location in the directories and sync it.  Also, add `genlisting.py` to your repo.  `genlisting.py` is used to create a web page that allows you to navigate the repo from a browser.

```
      # Login to GCS
      - name: Google Auth
        if: github.repository_owner == 'pyrsia' && (github.event_name == 'push' || github.event_name == 'release')
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/679352079717/locations/global/workloadIdentityPools/pyrsia-pool/providers/github-provider'
          service_account: 'pyrsia-ghaction@pyrsia-sandbox.iam.gserviceaccount.com'

      # Add gsutils
      - name: Set up Cloud SDK
        if: github.repository_owner == 'pyrsia' && (github.event_name == 'push' || github.event_name == 'release')
        uses: 'google-github-actions/setup-gcloud@v1'

      # Add the updated helm chart to the helm NIGHTLY repo
      - name: Add the updated helm chart to the helm NIGHTLY repo
        if: github.repository_owner == 'pyrsia' && (github.event_name == 'push' || github.event_name == 'release')
        run: |
          .github/workflows/chartmuseum.sh nightly

      # Add the updated helm chart to the helm STABLE repo
      - name: Add the updated helm chart to the helm STABLE repo
        if: github.repository_owner == 'pyrsia' && github.event_name == 'release'
        run: |
          .github/workflows/chartmuseum.sh stable
```

**Comment by karolh2000** [comment]
@sbtaylor15 I see the following code in chartmuseum.sh 

`gsutil -m rsync -r gs://helmrepo/repos repos`

For the vs code extension binaries, should we replace this line with a different `gs:` ? I'm guessing we don't want to store the vs code extension binaries in the pyrsia helm repo?

**Comment by karolh2000** [comment]
Heads up, this PR will be used to tests the GC scripts so I might need a few iteration to get it right.

**Comment by dasmanas** [comment]
@karolh2000 let me know if you need any help. I also made some improvement on the sync process to avoid downloading the whole set of files from Cloud Bucket to GitHub runner through https://github.com/pyrsia/pyrsia/pull/1580.

**Comment by karolh2000** [comment]
> pyrsia/pyrsia#1580

@dasmanas  Let's chat soon, I'll ping you later today, I think you might be able to help me with the GC auth error (GC auth is failing in the PR). Thanks!

**Comment by karolh2000** [comment]
This PR was moved to https://github.com/pyrsia/pyrsia-vscode-extension/pull/28 because of the github token issues for forks.

**Pull request closed without merging**
